/**
 * 이상형 월드컵 - 캐릭터 데이터
 * 로컬 이미지 사용 (즉시 로드)
 */

const CHARACTERS = {
    male: [
        { id: "m1", name: "강동원", img: "images/강동원.png" },
        { id: "m2", name: "공유", img: "images/공유.png" },
        { id: "m3", name: "규원", img: "images/규원.png" },
        { id: "m4", name: "김정은", img: "images/김정은.png" },
        { id: "m5", name: "김제동", img: "images/김제동.png" },
        { id: "m6", name: "남주혁", img: "images/남주혁.png" },
        { id: "m7", name: "덱스", img: "images/덱스.png" },
        { id: "m8", name: "디발라", img: "images/디발라.png" },
        { id: "m9", name: "류준열", img: "images/류준열.png" },
        { id: "m10", name: "마동석", img: "images/마동석.png" },
        { id: "m11", name: "무리뉴", img: "images/무리뉴.png" },
        { id: "m12", name: "박지성", img: "images/박지성.png" },
        { id: "m13", name: "백종원", img: "images/백종원.png" },
        { id: "m14", name: "뷔", img: "images/뷔.png" },
        { id: "m15", name: "세븐틴 민규", img: "images/세븐 틴민규.png" },
        { id: "m16", name: "손석구", img: "images/손석구.png" },
        { id: "m17", name: "손흥민", img: "images/손흥민.png" },
        { id: "m18", name: "신유열", img: "images/신유열.png" },
        { id: "m19", name: "연청조", img: "images/연청조.png" },
        { id: "m20", name: "오정세", img: "images/오정세.png" },
        { id: "m21", name: "오타니", img: "images/오타니.png" },
        { id: "m22", name: "원필", img: "images/원필.png" },
        { id: "m23", name: "이광수", img: "images/이광수.png" },
        { id: "m24", name: "이재명", img: "images/이재명.png" },
        { id: "m25", name: "이희준", img: "images/이희준.png" },
        { id: "m26", name: "일론머스크", img: "images/일론머스크.png" },
        { id: "m27", name: "제이디박", img: "images/제이디박.png" },
        { id: "m28", name: "차승원", img: "images/차승원.png" },
        { id: "m29", name: "최우식", img: "images/최우식.png" },
        { id: "m30", name: "최태원", img: "images/최태원.png" },
        { id: "m31", name: "하정우", img: "images/하정우.png" },
        { id: "m32", name: "현빈", img: "images/현빈.png" }
    ],
    female: [
        { id: "f1", name: "고윤정", img: "images2/고윤정.png" },
        { id: "f2", name: "김다미", img: "images2/김다미.png" },
        { id: "f3", name: "김연아", img: "images2/김연아.png" },
        { id: "f4", name: "김혜수", img: "images2/김혜수.png" },
        { id: "f5", name: "라미란", img: "images2/라미란.png" },
        { id: "f6", name: "리설주", img: "images2/리설주.png" },
        { id: "f7", name: "박보영", img: "images2/박보영.png" },
        { id: "f8", name: "박은빈", img: "images2/박은빈.png" },
        { id: "f9", name: "박주미", img: "images2/박주미.png" },
        { id: "f10", name: "비비", img: "images2/비비.png" },
        { id: "f11", name: "수지", img: "images2/수지.png" },
        { id: "f12", name: "식빵언니", img: "images2/식빵언니.png" },
        { id: "f13", name: "신세경", img: "images2/신세경.png" },
        { id: "f14", name: "신혜선", img: "images2/신혜선.png" },
        { id: "f15", name: "아이유", img: "images2/아이유.png" },
        { id: "f16", name: "안유진", img: "images2/안유진쌩얼.png" },
        { id: "f17", name: "이방카 트럼프", img: "images2/이방카트럼프.png" },
        { id: "f18", name: "이부진", img: "images2/이부진.png" },
        { id: "f19", name: "이성경", img: "images2/이성경.png" },
        { id: "f20", name: "이수지", img: "images2/이수지.png" },
        { id: "f21", name: "이주빈", img: "images2/이주빈.png" },
        { id: "f22", name: "장도연", img: "images2/장도연.png" },
        { id: "f23", name: "장원영", img: "images2/장원영쌩얼.png" },
        { id: "f24", name: "전종서", img: "images2/전종서.png" },
        { id: "f25", name: "전지현", img: "images2/전지현.png" },
        { id: "f26", name: "제니", img: "images2/제니.png" },
        { id: "f27", name: "추미애", img: "images2/추미애.png" },
        { id: "f28", name: "카리나", img: "images2/카리나.png" },
        { id: "f29", name: "하리수", img: "images2/하리수.png" },
        { id: "f30", name: "한소희", img: "images2/한소희.png" },
        { id: "f31", name: "화사", img: "images2/화사.png" },
        { id: "f32", name: "황우슬혜", img: "images2/황우슬혜.png" }
    ]
};
